---

- hosts: host
  become: true
  gather_facts: false 
  
  roles:
    # Install Required Packages
    - install_packages 
    # Nginx apt repository and installation
    - nginx_installation
    # Restarting service
    - service_restart
    # Create important directories
    - create_directories
    # Copying config files
    - configurations
