---

- name: update package list
  apt:
    update_cache: yes

- name: add nginx repository key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: add nginx repository
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ focal nginx
    state: present

- name: update package list
  apt:
    update_cache: yes

- name: install nginx package
  apt:
    name: nginx
  state: latest
  update_cache: yes