---

- name: copy nginx config file
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  

- name: copy php-fpm pool config file
  template:
    src: php-fpm-pool.j2
    dest: /etc/php/8.1/fpm/php-fpm.conf

- name: remove /etc/php/8.1/fpm/pool.d/www.conf
  file:
    path: /etc/php/8.1/fpm/pool.d/www.conf
    state: absent

- name: copy default pool configuration
  template:
    src: wwww.conf.j2
    # variable for hostname should be set
    dest: /etc/php/8.1/fpm/pool.d/www.conf

- name: copy php.ini config
  template:
    src: php-ini.j2
    dest: /etc/php/8.1/fpm/php.ini
  notify: restart_php
