- name: restart php-fpm
  notify: restart_php

- name: restart nginx
  notify: restart_nginx

- name: restart_php
  service:
    name: php-fpm
    state: restarted

- name: restart_nginx
  service:
    name: nginx
    state: restarted